### ISSUE TITLE
No device available in 0.2.0

### ISSUE THREAD

**Issue by Molodax** [kbirger/ha-smarter-integration#43]
## Version of the custom_component

0.2.0

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

It worked very well prior to update to 0.2.0. Since then the device (kettle) became unavailable. When I try to reinstall,  I'm able to add the component with my account but it is empty (no device)

## Debug log

```text

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:587
First occurred: 24 June 2024 at 17:30:41 (1 occurrences)
Last logged: 24 June 2024 at 17:30:41

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyrebase/pyre_sseclient.py", line 65, in __next__
    nextchar = next(self.resp_iterator)
               ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/pyrebase/pyrebase.py", line 664, in start_stream
    for msg in self.sse:
  File "/usr/local/lib/python3.12/site-packages/pyrebase/pyre_sseclient.py", line 69, in __next__
    self._connect()
  File "/usr/local/lib/python3.12/site-packages/pyrebase/pyrebase.py", line 625, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/usr/local/lib/python3.12/site-packages/pyrebase/pyre_sseclient.py", line 54, in _connect
    self.resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://smarter-live.firebaseio.com/devices/30001c7a690cfa50.json?auth=redacted

Also:

2024-06-24 17:07:55.127 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity None for domain binary_sensor with platform smarter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 743, in _async_add_entity
if entity.unique_id is not None:
^^^^^^^^^^^^^^^^
File "/config/custom_components/smarter/entity.py", line 60, in unique_id
return "-".join(
^^^^^^^^^
TypeError: str.join() takes exactly one argument (4 given)

```

**Comment by timthorn** [comment]
Same situation here, I'm afraid.

**Comment by Molodax** [comment]
Downgrade to the previous version solves the issue for me.

**Comment by acenuke** [comment]
> Downgrade to the previous version solves the issue for me.

Same issue for me. No device in 0.2.0 but all ok once downgraded to 0.1.4

**Comment by Molodax** [comment]
In case anyone is interested, the issue remains the same in 0.3.0-dev

**Comment by acenuke** [comment]
> In case anyone is interested, the issue remains the same in 0.3.0-dev

Actually it works for me, but all the entities names changed and the old ones are unavailable. I had to redo my dashboard

**Comment by Molodax** [comment]
> > In case anyone is interested, the issue remains the same in 0.3.0-dev
> 
> Actually it works for me, but all the entities names changed and the old ones are unavailable. I had to redo my dashboard

You are right, it has been fixed.
Thank you.
