### ISSUE TITLE
Error Setting up Smarter Integration with Ikettle V3 (SMKET01)

### ISSUE THREAD

**Issue by DeBendeBurcht** [kbirger/ha-smarter-integration#77]
Im unable to set up the integration oon v0.3.1 when logging in, it fails to set up, i log in using my email and password, and my ikettle v3 is connected to my account and accessible through the smarter app on my phone.

## Version of the custom_component

v0.3.1

## Configuration

```yaml
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 1:04:19 PM (2 occurrences)
Last logged: 1:06:57 PM

Error setting up entry myemail@gmail.com for smarter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarter/__init__.py", line 20, in async_setup_entry
    devices = await hub.discover_devices(user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarter/smarter_hub.py", line 70, in discover_devices
    return await self.hass.async_add_executor_job(_discover_devices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smarter/smarter_hub.py", line 63, in _discover_devices
    return list(
        itertools.chain.from_iterable(
    ...<2 lines>...
        )
    )
  File "/config/custom_components/smarter/smarter_hub.py", line 65, in <genexpr>
    load_from_network(network, user.identifier)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/smarter_client/managed_devices/__init__.py", line 13, in load_from_network
    network.fetch()
    ~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/smarter_client/domain/models.py", line 50, in fetch
    self._init_data()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/smarter_client/domain/models.py", line 357, in _init_data
    raise ex
  File "/usr/local/lib/python3.13/site-packages/smarter_client/domain/models.py", line 350, in _init_data
    key) for key in self._data.get('associated_devices')]
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

## Describe the bug

When i try setting up the smarter integration with my email and password (because my account has a space in its username) it logs in succesfully, but fails to set up, therefore producing the logs as described above

**Comment by kbirger** [comment]
Hi, sorry, Gmail spam listed GitHub and I didn't notice for months. 

If you are still interested in using the integration, please run this debug script and provide your output. 

https://github.com/kbirger/smarter-kettle-client/tree/dev/device_debug

Clone the repo on a machine that has Python, and install the requirements file in that folder. Follow the instructions in the __main__.py .

This output will allow me to see why your connection is failing. 

At face value, it looks like your account is not reporting any devices
